version: '3.8'

services:
  # Бекенд
  backend:
    build: ./backend
    env_file:
      - .env
    container_name: landscaping-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:

      # Настройки приложения
      SPRING_APPLICATION_NAME: "LandScaping WebSite"

      # Подключение к локальной БД на хосте
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # Настройки Liquibase
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: "classpath:liquibase/db.changelog-master.yaml"

      # Telegram Bot
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_ADMIN_CHAT_ID: ${TELEGRAM_ADMIN_CHAT_ID}
    ports:
      - "8080:8080"
    restart: unless-stopped
  # Фронтенд
  # ===================== FRONTEND =====================
  frontend:
    build: ./frontend
    container_name: landscaping-frontend
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=home-plant-mo.ru
      - LETSENCRYPT_HOST=home-plant-mo.ru
      - LETSENCRYPT_EMAIL=dragon-pg@yandex.ru
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped

  # ===================== HTTPS REVERSE PROXY =====================
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d

  # ===================== SSL AUTOGENERATOR =====================
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=dragon-pg@yandex.ru
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html